"""Editorial content for the portable VP Pessoas meeting HTML."""

def cards(items, cls=''):
    return '<div class="cards '+cls+'">'+''.join('<div class="card"><span class="eyebrow">'+a+'</span><h3>'+b+'</h3><p>'+c+'</p></div>' for a,b,c in items)+'</div>'

def flow(items, cls=''):
    return '<div class="flow '+cls+'">'+''.join('<div class="flow-step"><span class="step-n">'+str(i+1).zfill(2)+'</span><h3>'+a+'</h3><p>'+b+'</p></div>' for i,(a,b) in enumerate(items))+'</div>'

def table(heads, rows):
    return '<div class="table-wrap"><table><thead><tr>'+''.join('<th scope="col">'+x+'</th>' for x in heads)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(('<th scope="row">'+c+'</th>') if i==0 else '<td>'+c+'</td>' for i,c in enumerate(row))+'</tr>' for row in rows)+'</tbody></table></div>'

def takeaway(text):
    return '<div class="takeaway">'+text+'</div>'

def jump(id, label):
    return '<button class="drill" data-jump="'+id+'">'+label+' <span aria-hidden="true">↗</span></button>'

SLIDES=[]
def add(id, group, title, sub, body, *, sources=(), chapter=1, section=None, question='', bridge='', detail=(), kind='content', label='Análise / proposta', note=''):
    SLIDES.append(dict(id=id,group=group,title=title,sub=sub,body=body,sources=list(sources),chapter=chapter,section=section,question=question,bridge=bridge,detail=list(detail),kind=kind,label=label,note=note))

add('abertura','Percurso','IA para transformar<br>o trabalho.','Estratégia de IA da VP Pessoas · Visão 2028',
    '<p class="cover-thesis">Preparar a organização.<br>Reinventar os serviços de Pessoas.</p><div class="cover-meta">Vivo · Setembro de 2026<br>Proposta para discussão</div>',kind='cover',chapter=12,bridge='O percurso conecta trabalho, mercado, Vivo, direção e execução.')

add('percurso','Percurso','O percurso da conversa.','',
    '<div class="agenda-grid">'+''.join('<button data-map-group="'+g+'"><b>'+n+'</b><span><strong>'+g+'</strong><small>'+description+'</small></span></button>' for n,g,description in [('01','Percurso','Objetivo e caminho da conversa'),('02','Trabalho','Da tarefa ao resultado'),('03','Mercado','O que aprendemos com as empresas'),('04','Vivo','Bases existentes e conexões necessárias'),('05','Direção','Responsabilidades, visão e cinco big bets'),('06','Execução','Modelo, evolução e valor')])+'</div><div class="route-summary" id="route-summary"></div>',kind='agenda',chapter=12,bridge='Comecemos pelo que muda no trabalho com IA.',question='Qual tema precisa de mais espaço nesta conversa?')

add('trabalho-transicao','Trabalho','Trabalho','O que precisa mudar para a IA melhorar o resultado, além de acelerar uma tarefa?','<div class="transition-word" aria-hidden="true">02</div>',kind='transition',chapter=1,bridge='Uma conversa de desenvolvimento torna essa diferença concreta.')

add('trabalho','Trabalho','Uma tarefa mais rápida só cria valor<br>se melhorar o resultado.','Exemplo ilustrativo: a conversa de desenvolvimento de uma pessoa.',
    flow([('Preparar','IA reúne registros e produz uma primeira síntese.'),('Interpretar e conversar','O gestor confere evidências, acrescenta contexto e orienta.'),('Acompanhar','Os acordos viram ações e ajudam a melhorar a atuação.')])+
    '<div class="result-ribbon"><span>Apoio à tarefa</span><span>Qualidade do processo</span><strong>Desenvolvimento e entrega</strong></div>'+takeaway('O valor está no caminho completo: <strong>preparar → conversar → agir.</strong>'),
    question='Se a preparação ficar mais rápida, o que precisa mudar para a conversa ser melhor?',bridge='A transformação precisa ligar a tarefa ao resultado.',detail=['profundidade','beneficio','papeis'],note='Use o mesmo exemplo durante a abertura. Síntese pronta é uma entrega intermediária. O resultado desejado é orientação útil que se converte em desenvolvimento. Não atribuir ganhos numéricos a este exemplo.')

add('profundidade','Trabalho','A profundidade da mudança<br>depende do problema.','Três possibilidades para o mesmo exemplo. Cada uma exige condições diferentes.',
    cards([('Apoiar uma atividade','Uma síntese revisada','O ciclo funciona; reunir registros exige esforço demais.'),('Redesenhar o processo','Um ciclo mais útil','As dificuldades estão nas etapas, regras e passagens.'),('Criar uma capacidade','Apoio contínuo','A necessidade pede acompanhamento que o serviço atual não oferece.')],'three')+takeaway('Quanto maior a abrangência, maiores as exigências de dados, integração e manutenção.'),
    chapter=1,section='1.3',question='A dificuldade está em uma tarefa, no processo ou em uma capacidade que ainda precisamos criar?',bridge='Em qualquer alternativa, o benefício pode se perder entre as etapas.',note='As alternativas não constituem uma escada obrigatória de maturidade. Escolher a mais ampla precisa ser justificado pela necessidade e pelo custo de sustentação.')

add('beneficio','Trabalho','O ganho pode desaparecer<br>na espera e no retrabalho.','Observe o tempo até resolver a necessidade, além do tempo para produzir a primeira resposta.',
    '<div class="bottleneck"><div><span class="eyebrow">Preparação</span><h3>Síntese pronta</h3><p>A IA acelera esta etapa.</p></div><div class="friction"><span class="eyebrow">Passagens</span><h3>Falta informação.<br>É preciso revisar.<br>A decisão espera.</h3></div><div><span class="eyebrow">Beneficiário</span><h3>Orientação útil</h3><p>É aqui que o valor precisa chegar.</p></div></div>'+takeaway('Acompanhar <strong>esforço total + espera + revisão + qualidade</strong> torna a melhoria observável.'),chapter=1,section='1.4',question='Onde a resolução costuma parar hoje?',bridge='Precisamos tornar as responsabilidades visíveis.')

add('papeis','Trabalho','Quem faz o benefício<br>chegar ao final?','Mudar a execução afeta competências e decisões ao redor dela.',
    table(['Papel','Contribuição no exemplo'],[['Gestor','Conferir a síntese, acrescentar contexto e conduzir a conversa.'],['Especialista de Pessoas','Explicitar critérios de qualidade e apoiar o desenvolvimento.'],['Responsável pelo processo','Rever etapas e acompanhar o resultado completo.'],['Tecnologia e dados','Viabilizar informação, integrações e funcionamento.'],['Liderança da área','Criar condições de aprendizagem e orientar a capacidade liberada.']]),chapter=1,section='1.5',question='Qual responsabilidade ainda fica sem dono quando o trabalho atravessa áreas?',bridge='Com esses critérios, podemos ler o que o mercado está fazendo.')

add('mercado-transicao','Mercado','Mercado','Como as empresas conectam aprendizagem, trabalho, organização e capacidade de entrega?','<div class="transition-word" aria-hidden="true">03</div>',kind='transition',chapter=2,bridge='Cada referência contribui com uma peça desse raciocínio.')

add('mercado','Mercado','Cinco referências para conectar<br>a transformação.','Aprendizagem, recursos, redesenho, direção e autonomia se complementam.',
    '<div class="benchmark-grid">'+''.join('<button class="benchmark" data-jump="'+id+'"><span class="eyebrow">'+company+'</span><h3>'+title+'</h3><p>'+copy+'</p><span class="text-link">'+action+' ↗</span></button>' for id,company,title,copy,action in [
        ('bb-transicao','Banco do Brasil','Aprender no trabalho','Formação ligada ao contexto de cada função.','Abrir o caso'),
        ('meli-transicao','Mercado Livre','Compartilhar capacidades','Recursos para usar e construir soluções.','Abrir o caso'),
        ('nubank-transicao','Nubank','Redesenhar com as pessoas','Fluxos, competências e organização conectados.','Abrir o caso'),
        ('ifood-transicao','iFood','Ligar direção e entrega','Metas orientam produtos e sua evolução.','Abrir o caso'),
        ('toqan-transicao','Prosus / Toqan','Ampliar a autonomia','Conversa, dados e criação acessíveis.','Abrir o caso'),
        ('comparacao','Síntese dos casos','Comparar as funções','O que chega à pessoa e o que a empresa mantém.','Ver comparação')])+'</div>',
    sources=['BB','SRC-PUB-016','SRC-PER-002','SRC-PER-001','SRC-PUB-015','SRC-PUB-028'],chapter=3,question='Qual desses mecanismos mais ajudaria a conectar nossas iniciativas?',bridge='Cada referência ilumina uma conexão que a Vivo pode desenvolver.',detail=['comparacao'],label='Síntese de evidências',note='BB e Mercado Livre têm publicações oficiais. A estrutura de transformação do Nubank vem de resumo do evento de agosto de 2026. O modelo iFood vem de conversa com uma executiva, sem data confirmada. Prosus / Toqan combina produto público e experiência relatada no iFood. Não há comparação mensurada de velocidade entre empresas.')

add('bb-transicao','Mercado','Banco do Brasil','Aprendizagem: como ligar a formação ao trabalho de cada função?','<div class="transition-word" aria-hidden="true">01 / 05</div>',kind='transition',chapter=2,bridge='O caso mostra formação prática ligada ao contexto de uso.')

add('bb','Mercado','Aprender IA faz sentido<br>no contexto de cada função.','Banco do Brasil · AcademIA BB 2026',
    '<div class="split"><div class="stat-block"><strong>36 mil<span>+</span></strong><h3>inscritos</h3><p>Alcance informado pelo banco.<br>Inscrição mede interesse e acesso.</p></div><div>'+flow([('Reconhecer','Uma situação real da rotina.'),('Praticar','Aplicar os recursos de IA disponíveis.'),('Transferir','Levar a aprendizagem ao trabalho.')],'vertical')+'</div></div>'+takeaway('Para a Vivo: conectar formação, contexto de uso e evidência de aplicação.'),
    sources=['BB'],chapter=2,section='2.1',question='Em quais situações reais cada público precisa aprender a usar e a revisar IA?',bridge='Além de aprender, as pessoas precisam de recursos para aplicar.',label='Publicação corporativa',note='Mais de 36 mil inscritos é o dado publicado pelo BB. Não equivale a conclusão, domínio da competência ou ganho de produtividade. A sequência reconhecer–praticar–transferir é uma representação didática da implicação para a Vivo.')

add('meli-transicao','Mercado','Mercado Livre','Recursos: como aproximar o uso cotidiano da capacidade de construir soluções?','<div class="transition-word" aria-hidden="true">02 / 05</div>',kind='transition',chapter=2,bridge='Vamos distinguir experiência de uso, base de criação e competências.')

add('meli','Mercado','A experiência de uso e a base de criação<br>resolvem necessidades diferentes.','Mercado Livre · Peças documentadas com funções complementares.',
    '<div class="split"><div class="feature-panel"><span class="eyebrow">Para quem trabalha</span><h3>Cowork</h3><div class="big-number">31 mil</div><p>funcionários receberam acesso, segundo o resultado Q1/2026.</p><span class="evidence-note">Disponibilização não mede uso ativo.</span></div><div class="layers compact"><div><b>Verdi</b><span>Construir aplicações e agentes.</span></div><div><b>Serviços comuns</b><span>Busca, ferramentas, memória e acesso a modelos.</span></div><div><b>Fury e dados</b><span>Apoiar desenvolvimento e operação.</span></div></div></div>'+takeaway('As fontes documentam as peças. <strong>A conexão direta Cowork–Verdi permanece sem confirmação.</strong>'),
    sources=['SRC-PUB-019','SRC-PUB-017','SRC-PUB-016','SRC-PUB-018'],chapter=2,section='2.2',question='Quais capacidades nossos produtos poderiam compartilhar sem reconstruir as conexões?',bridge='As competências precisam evoluir com os recursos que passam a existir.',label='Publicações corporativas',detail=['meli-pessoas'])

add('meli-pessoas','Mercado','A transformação também chega<br>aos serviços e às competências.','Mercado Livre · Employee Support e avaliação de desenvolvedores.',
    '<div class="split"><div><span class="eyebrow">Self-service · declarado no 10-K 2025</span><div class="bar-chart"><div><b>Antes</b><span><i style="width:70%"></i></span><strong>70%</strong></div><div><b>Depois</b><span><i style="width:93%"></i></span><strong>93%</strong></div></div><p class="evidence-note">A empresa também reporta mais de 1,4 milhão de consultas anuais ao bot de Employee Support.</p></div><div class="feature-panel"><span class="eyebrow">Competência aplicada</span><h3>Avaliar com IA</h3><p>A newsletter de junho de 2026 descreve avaliação de desenvolvedores trabalhando com IA.</p><p>O recurso disponível passa a fazer parte do trabalho que se espera da pessoa.</p></div></div>',
    sources=['SRC-PUB-020','SRC-PUB-016'],chapter=2,section='2.2',question='Como seleção e desenvolvimento precisam acompanhar o trabalho com IA?',bridge='Recursos e competências se encontram no redesenho da organização.',label='Resultados declarados pela empresa',note='Não há evidência causal suficiente para transferir a variação de self-service para a Vivo. A abertura integral do 10-K havia excedido o limite do leitor na pesquisa do projeto; a catalogação registra essa limitação. Dados reproduzidos da estratégia vigente, com link ao documento original.')

add('nubank-transicao','Mercado','Nubank','Redesenho: como conectar infraestrutura, trabalho, talento e organização?','<div class="transition-word" aria-hidden="true">03 / 05</div>',kind='transition',chapter=2,bridge='A estratégia relatada no evento ganha forma no caso de performance.')

add('nubank','Mercado','Infraestrutura, trabalho e organização<br>participam da mesma transformação.','Nubank · AI Transformation Office, conforme resumo do HR Think Tank de agosto de 2026.',
    '<div class="three-pairs"><div><span>Condições para transformar</span><h3>Foundations</h3><p>Acesso e regras.</p><h3>Infra & Enablement</h3><p>Plataforma, engenharia e padrões.</p></div><div><span>Mudança no trabalho</span><h3>Workflows Reinvention</h3><p>Redesenho de fluxos completos.</p><h3>Talent & Organization</h3><p>Competências, papéis e estruturas.</p></div><div><span>Confiança e participação</span><h3>AI Risk</h3><p>Controles no desenvolvimento e uso.</p><h3>Communications</h3><p>Entendimento e mobilização.</p></div></div>'+takeaway('A contribuição de Pessoas alcança o trabalho, as competências e a organização.'),
    sources=['SRC-PER-002','SRC-PUB-029'],chapter=2,section='2.3',question='Quais conexões entre essas frentes precisamos explicitar na Vivo?',bridge='O caso de performance mostra como as frentes se encontram.',label='Relato de evento',detail=['performance','nubank-publico'],note='As seis frentes vêm do resumo pessoal do evento, derivado de transcrição e fotos. A publicação corporativa complementa a direção geral de dados, talento e cultura, mas não comprova essa estrutura. Não inferir um organograma final implantado.')

add('performance','Mercado','Primeiro se desenha o trabalho.<br>Depois se constrói a solução.','Nubank · Performance como aplicação da estratégia relatada no evento.',
    flow([('Desenho conjunto','12 executivos discutem princípios e experiência em uma oficina.'),('Piloto com IA','A solução organiza evidências e apoia a preparação da avaliação.'),('Revisão do gestor','A pessoa corrige, acrescenta contexto e responde pelo julgamento.')])+takeaway('O piloto relatou erros e lacunas de contexto. <strong>A revisão e a aprendizagem fazem parte do desenho.</strong>'),
    sources=['SRC-PER-002'],chapter=2,section='2.4',question='Que princípios do serviço precisam estar claros antes de automatizar etapas?',bridge='Além dos processos, vale distinguir os produtos e seu estágio real.',label='Relato de piloto',note='Fonte: resumo do HR Think Tank, seções 20–29, 40–46, 52–64 e 72–74. O número de executivos é do relato. Não usar esse caso como uma meta de ganho para a Vivo.')

add('nubank-publico','Mercado','Buscar conhecimento e reutilizar recursos<br>são contribuições diferentes.','Nubank · Duas publicações, dois públicos e estágios explícitos.',
    '<div class="split"><div class="feature-panel"><span class="eyebrow">AskNu · Maio de 2025</span><h3>Perguntar no Slack</h3><p>Busca documentos no Confluence e apresenta as fontes da resposta.</p><div class="small-stat"><strong>74%</strong><span>das respostas internas auditadas eram classificadas como precisas.</span></div><p class="evidence-note">Férias e contracheques apareciam como próximos passos.</p></div><div class="feature-panel"><span class="eyebrow">Catálogo de skills · Setembro de 2026</span><h3>Construir com recursos avaliados</h3><p>Desenvolvedores encontram pacotes de instruções e ferramentas para usar em agentes.</p><p>O Skill Vetter examina riscos antes da distribuição.</p></div></div>',
    sources=['SRC-PUB-021','SRC-PUB-022','SRC-PUB-029'],chapter=2,section='2.7',question='O que precisa ser verificado antes de uma capacidade ser usada por várias soluções?',bridge='Essa transformação exige direção para organizar a entrega.',label='Publicações de engenharia',note='Acesso geral a IA não comprova um aplicativo único para conversar, criar e agir. Vagas de engenharia descrevem escopo de construção; não são prova de implantação universal. Não afirmar entrega das ações futuras do AskNu.')

add('ifood-transicao','Mercado','iFood','Direção: como metas e produtos organizam o trabalho que precisa ser entregue?','<div class="transition-word" aria-hidden="true">04 / 05</div>',kind='transition',chapter=2,bridge='O benchmark ajuda a discutir a função responsável por organizar a evolução.')

add('ifood','Mercado','A direção antecede a organização<br>das demandas.','iFood · Mecanismo descrito em conversa com uma executiva.',
    flow([('Direção estratégica','A liderança funcional orienta resultados e escolhas.'),('Produtos e capacidade','O planejamento orienta alocação e campo de atuação.'),('Escolhas do PM','PMs consolidam necessidades, organizam a evolução e articulam a entrega.')])+takeaway('As áreas continuam identificando necessidades. <strong>A tradução em trabalho de produto tem uma função responsável.</strong>'),
    sources=['SRC-PER-001'],chapter=2,section='2.5',question='Que direção já deveria estar definida quando uma necessidade chega ao produto?',bridge='A direção organiza o trabalho; a experiência de uso amplia a autonomia.',label='Benchmark por conversa',note='Localizadores: Participante 2, 05:32–09:59 e 24:57–27:40. A data da conversa não está confirmada. O iFood faz escolhas de prioridade e de roadmap. O relato não demonstra superioridade mensurada de velocidade.')

add('toqan-transicao','Mercado','Prosus / Toqan','Autonomia: como uma experiência conversacional aproxima necessidade, dados e criação?','<div class="transition-word" aria-hidden="true">05 / 05</div>',kind='transition',chapter=2,bridge='A proposta pública do produto se conecta à experiência relatada no iFood.')

add('toqan','Mercado','Uma conversa pode aproximar<br>necessidade, dados e criação.','Toqan / Prosus · Proposta pública do produto e experiência relatada no iFood.',
    '<div class="conversation"><div class="human-bubble">“Quero entender este indicador e criar um apoio para minha rotina.”<small>Exemplo didático de intenção</small></div><div class="connector">A experiência compreende o pedido e mobiliza os recursos disponíveis.</div><div class="capabilities"><span>Conversa</span><span>Análise de dados</span><span>Criação de recursos</span></div></div>'+takeaway('Por trás da simplicidade: <strong>definições de negócio, conexões, permissões e manutenção.</strong>'),
    sources=['SRC-PER-001','SRC-PUB-015','SRC-PUB-028'],chapter=2,section='2.6',question='O que uma pessoa deveria conseguir fazer sem precisar conhecer a estrutura dos sistemas?',bridge='Vejamos o que cada referência oferece à pessoa e exige da empresa.',label='Produto público + benchmark',note='O produto público confirma a proposta. A configuração com dados no iFood vem da conversa: 12:02–18:48, 19:52–20:24 e 33:23–38:47. O relato menciona Databricks. Relação com Data Mesh é interpretação arquitetural, não prova de acesso irrestrito. Números de escala adicionais não confirmados foram excluídos.')

add('comparacao','Mercado','O que a pessoa usa.<br>O que a empresa precisa manter.','Compare as funções concretas. Clique para alternar o ponto de vista.',
    '<div class="segmented view-tabs" role="group" aria-label="Ponto de vista da comparação"><button data-compare="pessoa" aria-pressed="true">Na experiência da pessoa</button><button data-compare="empresa" aria-pressed="false">Por trás da experiência</button></div><div id="comparison-content"></div>',
    sources=['SRC-PUB-015','SRC-PUB-028','SRC-PUB-019','SRC-PUB-017','SRC-PUB-021','SRC-PUB-022','SRC-PUB-029'],chapter=3,section='3.1',question='Quais funções queremos oferecer à pessoa e quais recursos precisam ser compartilhados?',bridge='Esses aprendizados orientam a leitura das bases da Vivo.',label='Comparação de evidências',note='Não há ranking de sofisticação. Públicos e estágios diferem. As duas tabelas completas estão na leitura aprofundada. Permanecem sem confirmação a integração direta Cowork–Verdi, a execução das ações futuras do AskNu e uma ferramenta de criação sem programação disponível para qualquer funcionário do Nubank.')

add('vivo-transicao','Vivo','Vivo','O que os aprendizados do mercado nos ajudam a enxergar nas bases que já temos?','<div class="transition-word" aria-hidden="true">04</div>',kind='transition',chapter=4,bridge='Reconhecer as iniciativas existentes é o ponto de partida.')

add('bases','Vivo','Os movimentos já existem.<br>A conexão é a construção estratégica.','A direção corporativa de IA está documentada. Na VPP, cinco movimentos oferecem uma base.',
    '<div class="base-list">'+''.join('<div><span class="base-dot">'+str(i)+'</span><h3>'+a+'</h3><p>'+b+'</p><span class="base-purpose">'+c+'</span></div>' for i,(a,b,c) in enumerate([
        ('Eu Vivo IA','Formação e mobilização; avançar na aplicação ao trabalho.','Preparação'),('Data Mesh','Produtos Headcount e Skills, com expansão e validações em andamento.','Conhecimento'),('Violeta','Base de agentes por código no contexto relatado da VPP.','Capacidade técnica'),('COMP','Reconstrução de jornadas com IA no centro, desde a origem.','Reinvenção'),('Jeito de Produtar','Conexão em evolução entre visão, metas, produtos e capacidade.','Direção e entrega')],1))+'</div>',
    sources=['SRC-PUB-014','SRC-PER-005','SRC-PER-007'],chapter=4,section='4.2',question='Onde esses movimentos já se encontram e onde ainda dependem de conexões pontuais?',bridge='A contribuição de Pessoas parte dessas bases e da direção corporativa.',label='Direção publicada + contexto informado',detail=['vivo-corporativa','lacunas'],note='Não tratar Tech Product de agentes como implantado, COMP como concluída ou infraestrutura como autonomia já disponível ao usuário. A ausência de experiência integrada se refere ao contexto relatado da VPP. Avaliar o Violeta por capacidade e integração.')

add('vivo-corporativa','Vivo','A contribuição de Pessoas parte<br>da direção corporativa existente.','Relato Integrado Vivo 2025 · Vivo IA Digital e aplicação na operação.',
    '<div class="split"><div class="stat-block"><strong>19,6 mil</strong><h3>atendentes</h3><p>Copiloto apoiado em documentos internos, em lojas e call center, segundo o relato.</p></div><div class="feature-panel"><span class="eyebrow">Resultado publicado</span><div class="big-number">−10%</div><h3>tempo de atendimento via chat</h3><p>Referência da operação descrita no relatório; não constitui meta para Pessoas.</p></div></div>'+takeaway('Pessoas contribui com aprendizagem aplicada, liderança e mudanças nas responsabilidades.'),
    sources=['SRC-PUB-014'],chapter=4,section='4.1',question='Que prioridades do negócio exigem novas competências ou formas de trabalhar?',bridge='Para desdobrar essa direção, vale observar como a demanda se torna trabalho.',label='Resultado declarado pela Vivo',note='Fonte: Relato Integrado 2025, pp. 37 e 73–76. Direção de IA e pilares estratégicos já são públicos. Validar o desdobramento, a execução e as interfaces da VP.')

add('lacunas','Vivo','Parte da dificuldade da fila<br>começa antes da fila.','Comparação do mecanismo relatado no iFood com a situação descrita na Vivo.',
    '<div class="comparison-lanes"><div><span class="eyebrow">iFood · relato</span><h3>Direção → produto → escolhas do PM</h3><p>Metas e alocação delimitam a evolução dos produtos.</p></div><div><span class="eyebrow">Vivo · situação descrita</span><h3>Pedidos → qualificação → disputa de capacidade</h3><p>A entrada pode acumular reconstrução de problema, valor e prioridade.</p></div></div>'+takeaway('Hipótese para a VPP: <strong>metas claras e responsabilidade de produto reduzem a rediscussão a cada pedido.</strong>'),
    sources=['SRC-PER-001','SRC-PER-005','SRC-PER-007'],chapter=4,section='4.3',question='Quais decisões de direção a qualificação está tentando resolver repetidamente?',bridge='Esse ponto de partida define as escolhas para a VP Pessoas.',label='Leitura comparativa',note='Não afirmar ausência de planejamento na Vivo nem ausência de priorização no iFood. Tempos e responsabilidades do fluxo Vivo precisam de validação. A comparação não mede velocidade relativa.')

add('direcao-transicao','Direção','Direção','Das bases existentes à mudança que queremos produzir: qual deve ser a contribuição de Pessoas?','<div class="transition-word" aria-hidden="true">05</div>',kind='transition',chapter=5,bridge='Duas responsabilidades conectam a transformação da Vivo à atuação da VP.')

add('mandatos','Direção','Pessoas prepara a Vivo para mudar<br>e transforma a própria atuação.','Duas responsabilidades propostas que se reforçam.',
    '<div class="mandates"><div><span class="eyebrow">Para a organização</span><h3>Preparar para<br>o trabalho com IA</h3><p>Competências, aprendizagem e líderes capazes de reorganizar o trabalho.</p><span>Com negócio, lideranças e tecnologia.</span></div><div><span class="eyebrow">Na VP Pessoas</span><h3>Reinventar serviços<br>e decisões de Pessoas</h3><p>Processos mais simples e apoio com informação confiável.</p><span>Com especialidades, HR Tech e Data.</span></div></div>'+takeaway('Fora de RH, o responsável pela operação continua respondendo pelo resultado.'),
    chapter=5,question='Em quais decisões Pessoas lidera e em quais contribui com o negócio?',bridge='As responsabilidades e os aprendizados do percurso dão sentido à visão.',detail=['interfaces'])

add('derivacao','Direção','Dos aprendizados aos resultados<br>que queremos produzir.','Aprendizado do mercado → base ou necessidade Vivo → resultado pretendido.',
    table(['Aprendizado','Base ou necessidade Vivo','Resultado'],[['Redesenhar o trabalho e o papel humano','COMP e evolução dos serviços','Trabalho mais simples'],['Aprender e aplicar no contexto da função','Eu Vivo IA e dados de Skills','Pessoas mais preparadas'],['Ligar direção, produto e capacidades comuns','Jeito de Produtar, Data Mesh e Violeta','Entregas melhores']]),chapter=6,question='Que conexão precisa ficar mais forte para a visão ser realizável?',bridge='Essas conexões se traduzem em três resultados para a visão de 2028.')

add('visao','Direção','Trabalho mais simples.<br>Pessoas mais preparadas.<br>Entregas melhores.','Visão 2028 · IA integrada à preparação da organização e aos serviços de Pessoas.',
    '<div class="vision-bases"><span>Objetivos claros</span><span>Conhecimento confiável</span><span>Experiência acessível</span></div>',
    chapter=6,kind='vision',question='Esses três resultados expressam a mudança que queremos produzir até 2028?',bridge='Agora precisamos definir as escolhas que sustentam esses resultados.',detail=['derivacao'],note='A visão é uma proposta derivada do percurso, não um diagnóstico ou compromisso já aprovado. Trabalho mais simples se liga ao redesenho; pessoas preparadas à aprendizagem aplicada; entregas melhores à conexão entre metas, produtos e capacidades.')

add('apostas-transicao','Direção','Da visão às escolhas.','Quais compromissos tornam possíveis um trabalho mais simples, pessoas mais preparadas e entregas melhores?','<div class="transition-word" aria-hidden="true">Big bets</div>',kind='transition',chapter=7,bridge='As cinco big bets formam um conjunto: direção, experiência, conhecimento, preparação e reinvenção.')

add('apostas','Direção','Cinco big bets para construir<br>uma capacidade duradoura.','Objetivos orientam o trabalho; as demais big bets criam condições para realizá-lo.',
    '<div class="bets-system"><button class="bet-primary" data-jump="metas"><b>01</b><span><strong>Estratégia e metas na origem</strong><small>Resultados orientam produtos e capacidade.</small></span><i>↗</i></button><div class="bet-grid">'+''.join('<button data-jump="'+id+'"><b>'+n+'</b><h3>'+t+'</h3><p>'+c+'</p><span aria-hidden="true">↗</span></button>' for id,n,t,c in [('experiencia','02','Experiência integrada','Usar, criar e agir com autonomia.'),('conhecimento','03','Conhecimento reutilizável','Dados, definições e recursos confiáveis.'),('preparacao','04','Preparação da organização','Competências, liderança e talento.'),('reinvencao','05','Reinvenção dos serviços','IA desde a concepção do trabalho.')])+'</div></div>',
    chapter=7,question='Qual conexão entre as big bets está mais frágil hoje?',bridge='As cinco escolhas precisam se reforçar para sustentar a visão.',note='As big bets são compromissos estruturais aplicáveis a várias jornadas. Responsabilidade, qualidade e acompanhamento de valor atravessam as cinco. Não antecipar uma escolha de duas jornadas como se ela já definisse a estratégia.')

add('metas','Direção','A meta precisa orientar<br>o trabalho que entra no produto.','Big bet 01 · Estratégia e metas como origem do trabalho.',
    flow([('Resultado estratégico','Que mudança a VP precisa produzir?'),('Produto e responsável','Quem organiza a evolução para entregar esse resultado?'),('Capacidade e escolhas','Onde investir, o que sequenciar e o que adiar?')])+takeaway('O Jeito de Produtar pode institucionalizar essa ligação no planejamento e na carteira.'),
    chapter=7,section='7.1',sources=['SRC-PER-001','SRC-PER-005'],question='Conseguimos explicar nossa carteira pelos resultados que queremos produzir?',bridge='A meta orienta qual experiência precisamos oferecer.')

add('experiencia','Direção','A pessoa expressa a necessidade.<br>A experiência conecta os recursos.','Big bet 02 · Usar, criar e agir em uma experiência acessível.',
    '<div class="experience-map"><div class="intent"><span class="eyebrow">Exemplo de experiência desejada</span><h3>“Quero preparar a conversa<br>de desenvolvimento.”</h3><p>Proposta ilustrativa para a VPP.</p></div><div class="experience-bridge">Entender a intenção<br><span aria-hidden="true">↓</span></div><div class="experience-tools"><div><b>Encontrar</b><p>Dados e orientações, respeitando o acesso.</p></div><div><b>Apoiar</b><p>Organização de evidências e próximos passos.</p></div><div><b>Criar</b><p>Um recurso para a rotina, com avaliação.</p></div></div></div>'+takeaway('A pessoa confere fontes e limites. <strong>Julgamento e responsabilidade continuam explícitos.</strong>'),
    chapter=8,question='Qual ajuda seria útil sem exigir que a pessoa conheça os sistemas por trás?',bridge='Uma experiência confiável depende de conhecimento compartilhado.',detail=['camadas','conhecimento'],note='Este é um desenho proposto, não uma demonstração de sistema integrado ou ferramenta funcional. Não pressupõe um fornecedor, uma interface única nem construção integral própria.')

add('conhecimento','Direção','Manter uma vez.<br>Servir a várias necessidades.','Big bet 03 · Dados, conhecimento e ações como patrimônio reutilizável de Pessoas.',
    '<div class="reuse"><div class="reuse-core"><span class="eyebrow">Capacidade comum · exemplo proposto</span><h3>Consultar informação de férias</h3><p>Definição clara · acesso · responsável · atualização · avaliação</p></div><div class="reuse-lines" aria-hidden="true"></div><div class="reuse-consumers"><div><b>Assistente da pessoa</b><p>Responder uma dúvida.</p></div><div><b>Apoio ao gestor</b><p>Consultar informação autorizada.</p></div><div><b>Serviço de Pessoas</b><p>Usar a mesma regra no processo.</p></div></div></div>'+takeaway('Um catálogo torna os recursos encontráveis; avaliação e manutenção preservam sua utilidade.'),
    chapter=7,section='7.3',sources=['SRC-PUB-022','SRC-PER-005'],question='Que informação ou regra estamos reconstruindo em mais de uma solução?',bridge='As pessoas precisam aprender a aplicar e revisar esses recursos.',label='Proposta inspirada em evidências',note='A consulta de férias é um exemplo proposto para a VPP, não uma integração existente. A inspiração do marketplace Nubank é a avaliação de componentes antes da distribuição a desenvolvedores. Aplicar a lógica a Pessoas requer controles próprios ao impacto.')

add('preparacao','Direção','Preparar a organização é fazer<br>o aprendizado mudar o trabalho.','Big bet 04 · Aprendizagem, liderança e práticas de talento conectadas.',
    '<div class="learning-loop"><div><b>01</b><h3>Aprender no contexto</h3><p>Função, tarefa e situação real.</p></div><div><b>02</b><h3>Aplicar e revisar</h3><p>Execução com julgamento.</p></div><div><b>03</b><h3>Evoluir o trabalho</h3><p>Papéis e competências mudam.</p></div><div><b>04</b><h3>Atualizar práticas</h3><p>Seleção, mobilidade e desenvolvimento.</p></div></div>'+takeaway('Eu Vivo IA pode conectar formação à aplicação e às necessidades de cada público.'),
    chapter=7,section='7.4',sources=['BB','SRC-PUB-016','SRC-PER-002','SRC-PER-005'],question='Que evidência mostraria competência aplicada, além da participação na formação?',bridge='A própria VP aplica essa aprendizagem ao redesenho dos serviços.')

add('reinvencao','Direção','Reinventar serviços deve se tornar<br>uma capacidade de Pessoas.','Big bet 05 · IA desde a concepção, com aprendizagem que permanece.',
    '<div class="split"><div class="feature-panel"><span class="eyebrow">Movimento existente · COMP</span><h3>Reconstruir desde a origem</h3><p>Recrutamento interno e offboarding exemplificam jornadas redesenhadas com IA no centro.</p><p class="evidence-note">Integrações avançando não equivalem à transformação concluída.</p></div><div>'+flow([('Definir','Necessidade, experiência e papel humano.'),('Redesenhar','Regras, etapas e responsabilidades.'),('Sustentar','Qualidade, conhecimento e evolução.')],'vertical')+'</div></div>',
    chapter=7,section='7.5',sources=['SRC-PER-005','SRC-PER-007','SRC-PER-002'],question='Qual conhecimento precisa permanecer na VP depois da atuação de um parceiro?',bridge='O que essas big bets precisam compartilhar para funcionar?')

add('capacidades-transicao','Direção','O que as big bets<br>precisam compartilhar?','Depois de definir o que queremos construir, podemos discutir as capacidades que sustentam esse conjunto.','<div class="transition-word" aria-hidden="true">Bases</div>',kind='transition',chapter=8,bridge='Da experiência às bases técnicas: cada camada precisa de cobertura e responsável.')

add('camadas','Direção','Quatro camadas.<br>Quatro decisões de capacidade.','Capacidades que sustentam as big bets. Clique em uma camada para discutir sua cobertura.',
    '<div class="architecture">'+''.join('<button data-layer="'+str(i)+'"><b>0'+str(4-i)+'</b><span><strong>'+t+'</strong><small>'+c+'</small></span><span aria-hidden="true">+</span></button>' for i,(t,c) in enumerate([('Experiência do usuário','Conversar, encontrar, criar e solicitar ações.'),('Construção e coordenação','Criar agentes, combinar etapas e intervenção humana.'),('Capacidades reutilizáveis','Conhecimento, produtos de dados, ferramentas e ações.'),('Fundação de IA','Modelos, identidade, segurança e operação.')]))+'</div><div id="layer-detail" class="layer-detail" aria-live="polite">Selecione uma camada para discutir sua cobertura e responsabilidade.</div>',
    chapter=8,section='8.2',question='O que o ecossistema corporativo já cobre e o que precisa ser complementado?',bridge='Com as capacidades claras, podemos organizar quem decide e quem entrega.',note='Data Mesh participa dos produtos de dados. Violeta deve ser avaliado por cobertura real, incluindo construção e outras camadas. Não supor que um único componente resolverá todas as lacunas. Mais de uma interface pode compartilhar identidade, conhecimento e ferramentas.')

add('execucao-transicao','Execução','Execução','Como transformar a direção em responsabilidades, evolução dos produtos e evidências de valor?','<div class="transition-word" aria-hidden="true">06</div>',kind='transition',chapter=9,bridge='O modelo operativo organiza as decisões e a capacidade de entrega.')

add('modelo','Execução','Metas orientam produtos.<br>Produtos organizam a capacidade.','Modelo operativo proposto · decisões claras do planejamento à evolução contínua.',
    '<div class="operating">'+''.join('<div><span>'+n+'</span><h3>'+a+'</h3><p>'+b+'</p></div>' for n,a,b in [('01','Estratégia e metas','Definir resultados e escolhas de investimento.'),('02','Gestão de produto','PMs consolidam necessidades e organizam a evolução.'),('03','Especialidades','Contribuir com critérios, políticas e conhecimento do trabalho.'),('04','Capacidades compartilhadas','Manter experiência, dados, recursos e operação.')])+'</div>'+takeaway('A hipótese de velocidade: <strong>menos rediscussão, transferência de contexto e reconstrução de recursos.</strong>'),
    chapter=9,question='Quais direitos de decisão precisam ficar explícitos entre liderança funcional, PMs e times técnicos?',bridge='Responsabilidades claras transformam metas em evolução contínua.',detail=['interfaces'],note='Ownership inclui o acompanhamento do resultado e da evolução do produto ao longo do tempo. Parceiros contribuem com redesenho e construção; a VPP preserva direção e conhecimento. Velocidade deve ser observada pelo tempo até uma melhora útil, com qualidade.')

add('interfaces','Execução','A responsabilidade precisa acompanhar<br>a transformação até a operação.','Proposta de interfaces para discutir nas instâncias existentes.',
    table(['Quem','Responsabilidade proposta'],[['Negócio','Definir necessidade e responder pelo resultado da operação.'],['Pessoas','Apoiar competências, liderança e impactos no trabalho.'],['Tecnologia e dados','Assegurar recursos, integração, dados e condições de operação.'],['Segurança e privacidade','Participar das decisões conforme o uso e os dados envolvidos.']])+takeaway('Explicitar <strong>quem decide, quem disponibiliza capacidade e quem sustenta depois do teste.</strong>'),chapter=5,section='5.2',question='Qual decisão ou capacidade está sem atendimento nas interfaces atuais?',bridge='Com as responsabilidades definidas, podemos sequenciar a evolução.')

add('trajetoria','Execução','Conectar. Incorporar. Ampliar.','Movimentos estratégicos que se reforçam; o detalhamento depende de metas e capacidade.',
    '<div class="trajectory">'+''.join('<div><span>'+n+'</span><h3>'+t+'</h3><p>'+c+'</p><div class="signal"><b>Sinal de avanço</b>'+s+'</div></div>' for n,t,c,s in [('01','Conectar','Ligar as bases existentes e os investimentos à direção da VP.','A carteira se explica pelas cinco big bets.'),('02','Incorporar','Trazer produto, experiência integrada e preparação para o cotidiano.','As áreas usam capacidades comuns com responsáveis claros.'),('03','Ampliar e renovar','Reaproveitar conhecimento e rever serviços e práticas conforme o trabalho muda.','O aprendizado de uma transformação fortalece outras.')])+'</div>',
    chapter=10,question='O que precisa estar conectado para o próximo movimento fazer sentido?',bridge='O avanço precisa ser demonstrado por mudanças no trabalho e nas entregas.',note='Os movimentos orientam a evolução das capacidades. Jornadas decorrem de metas, relevância e capacidade. Não fixar onboarding ou qualquer primeira jornada sem esse desdobramento.')

add('valor','Execução','O valor aparece na mudança<br>do trabalho e da entrega.','As medidas e metas partem da situação inicial; o acompanhamento inclui custo total e qualidade.',
    table(['Resultado da visão','O que observar','Pergunta de valor'],[['Trabalho mais simples','Esforço total, espera, retrabalho e resolução.','A necessidade foi resolvida com menos esforço e qualidade preservada?'],['Pessoas mais preparadas','Aplicação, julgamento e adaptação do trabalho.','A pessoa consegue executar e revisar melhor?'],['Entregas melhores','Tempo até uma melhoria útil, qualidade e continuidade.','O produto realiza o objetivo e consegue evoluir?']])+takeaway('Tempo liberado exige destino explícito. <strong>Não se converte automaticamente em redução de despesa.</strong>'),
    chapter=11,question='Qual mudança verificável mostraria que a estratégia está produzindo valor?',bridge='Esses sinais orientam o que manter e o que ajustar na estratégia.',detail=['revisao'])

add('revisao','Execução','Os resultados também dizem<br>quando precisamos ajustar a estratégia.','Sinais de atenção e respostas possíveis, derivados das cinco big bets.',
    table(['Se observarmos…','Precisamos investigar…','Ajuste possível'],[['Acesso cresce, aplicação não','Contexto de uso, experiência e preparo','Rever apoio, aprendizagem e utilidade.'],['Criação cresce, qualidade não','Definições, avaliação e manutenção','Fortalecer conhecimento e sustentação.'],['A entrega continua fragmentada','Direção, responsabilidade e dependências','Reforçar metas, gestão de produto e capacidade comum.']]),
    chapter=11,question='Que resultado nos faria rever uma big bet ou sua forma de execução?',bridge='A discussão final pode registrar escolhas e o que ainda depende de evidência.')

add('discussao','Execução','Três perguntas para consolidar<br>a direção e seu desdobramento.','Registre convergências, ajustes e pontos que precisam de evidência.',
    '<div class="discussion-prompts"><div><b>01</b><h3>A visão expressa a mudança que queremos?</h3><p>Trabalho, preparação das pessoas e qualidade das entregas.</p></div><div><b>02</b><h3>As cinco big bets estão conectadas?</h3><p>Onde concentrar atenção para que uma capacidade fortaleça outra.</p></div><div><b>03</b><h3>O que precisamos esclarecer para desdobrá-las?</h3><p>Metas, responsabilidades, cobertura das bases e capacidade disponível.</p></div></div>',
    chapter=12,question='Quais ajustes, responsáveis e próximos esclarecimentos ficam registrados?',bridge='A estratégia mantém juntas a preparação da organização e a reinvenção de Pessoas.',note='Perguntas de facilitação; não presumem endosso, aprovação ou seleção de jornadas. Use o caderno para registrar a discussão e exportar as notas ao final.')

add('encerramento','Execução','Preparar a organização.<br>Reinventar Pessoas.','Uma estratégia de IA que conecta direção, autonomia e capacidade de transformação.',
    '<div class="closing-outcomes"><span>Trabalho mais simples</span><span>Pessoas mais preparadas</span><span>Entregas melhores</span></div><p class="closing-horizon">Visão 2028</p>',kind='close',chapter=12,question='O que levamos desta conversa?',bridge='Retome qualquer tema pelo mapa ou abra a biblioteca de fontes.')

from strategy_map import revise
revise(SLIDES, add, cards, takeaway, table)

from narrative_revision import revise_narrative, EXEC
revise_narrative(SLIDES, add, cards, takeaway, table)
ROUTES={"executivo":EXEC,"estendido":[s["id"] for s in SLIDES]}

COMPARE={
 'pessoa':table(['Situação','Prosus / Toqan','Mercado Livre','Nubank'],[['Começar a usar','Conversar para pesquisar, analisar e criar.','Cowork disponibilizado a funcionários.','Perguntar ao AskNu no Slack; acesso geral a ferramentas de IA.'],['Encontrar informação','Agente identifica dados, analisa e responde.','Serviço de busca em documentos e bases para aplicações.','AskNu busca no Confluence e mostra as fontes.'],['Receber apoio no trabalho','Agente analisa desempenho de restaurantes no iFood.','Verdi permite combinar informações e acionar sistemas.','AskNu responde dúvidas; ações eram ampliação planejada.']]),
 'empresa':table(['Capacidade','Prosus / Toqan','Mercado Livre','Nubank'],[['Permitir criação','Descrever em linguagem comum o recurso desejado.','Verdi: linguagem natural, regras e recursos técnicos.','Fontes detalham engenharia; criação geral sem programação não esclarecida.'],['Compartilhar recursos','Agente de dados atende pessoas e outros agentes.','Ferramentas comuns podem ser combinadas entre soluções.','Catálogo de skills para desenvolvedores.'],['Verificar acesso e riscos','Permissões do usuário no relato iFood.','Controles de segurança e uso de modelos e ferramentas.','Skill Vetter avalia riscos antes da distribuição.']])
}

LAYERS=[
 '<strong>Decisão de experiência:</strong> como oferecer uma interação coerente nos canais de trabalho, sem exigir que o usuário conheça os sistemas? Mais de uma interface pode compartilhar a mesma base.',
 '<strong>Decisão de construção:</strong> como especialistas e outros criadores poderão construir, testar e manter agentes? Avaliar a cobertura real do Violeta e os meios acessíveis a não especialistas.',
 '<strong>Decisão de patrimônio comum:</strong> o que manter como dados, conhecimento, ferramentas e ações compartilhadas? Data Mesh é parte dessa base; políticas, definições e responsáveis também são necessários.',
 '<strong>Decisão de fundação:</strong> quais serviços corporativos de modelos, identidade, segurança e operação atenderão aos produtos de Pessoas e com quais condições de continuidade?'
]
