'use strict';
const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const byId = Object.fromEntries(DATA.slides.map(s=>[s.id,s]));
const plain = s => {const el=document.createElement('div');el.innerHTML=s;return el.textContent.replace(/\s+/g,' ').trim();};
const esc = s => String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='vpp-ia-reuniao-notas-v1';
let notes={}, canStore=true, mode='executivo', current='abertura', trail=[], sourceFilter='all', comparison='pessoa', lastFocus=null, toastTimer;
try{notes=JSON.parse(localStorage.getItem(KEY)||'{}');if(!notes||typeof notes!=='object'||Array.isArray(notes))notes={};}catch{canStore=false;notes={};}
function route(){return DATA.routes[mode];}
function active(){return byId[current];}
function announce(message){$('#live-status').textContent=message;}
function toast(message){const el=$('#toast');el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4200);}
function scaleDeck(){const box=$('#deck').getBoundingClientRect();document.documentElement.style.setProperty('--scale',Math.max(.1,Math.min((box.width-32)/1280,(box.height-22)/720)));}
function position(){const ids=route();let idx=ids.indexOf(current);if(idx<0&&trail.length)idx=ids.indexOf(trail[0]);return idx;}
function navigation(){return trail.length?DATA.routes.estendido:route();}
function modeLabel(){return mode==='executivo'?'Executivo':'Estendido';}
function setHash(replace=false){const params=new URLSearchParams({modo:mode,quadro:current});if(trail.length)params.set('voltar',trail.join(','));const hash='#'+params.toString();try{history[replace?'replaceState':'pushState'](null,'',hash);}catch{location.hash=hash;}}
function parseHash(){
  const p=new URLSearchParams(location.hash.slice(1)),requested=p.get('modo'),legacy={'20':'executivo','120':'estendido','240':'estendido'};
  mode=DATA.routes[requested]?requested:(legacy[requested]||'executivo');
  current=byId[p.get('quadro')]?p.get('quadro'):'abertura';
  trail=[...new Set((p.get('voltar')||'').split(',').filter(x=>byId[x]&&x!==current))];
  if(!route().includes(current)&&!trail.length){
    const order=DATA.routes.estendido,index=order.indexOf(current);
    trail=[[...route()].reverse().find(id=>order.indexOf(id)<index)||'percurso'];
  }
}
function render(){
  $$('section.vpp-slide').forEach(el=>{const isActive=el.id===current;el.classList.toggle('active',isActive);el.setAttribute('aria-hidden',String(!isActive));el.inert=!isActive;el.classList.toggle('print-skip',!route().includes(el.id));});
  $$('[data-mode]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.mode===mode)));
  const idx=position(),r=route(),s=active(),ids=navigation(),navIndex=ids.indexOf(current),progress=Math.round(Math.max(0,idx+1)/r.length*100);
  $('#slide-position').textContent=`${progress}%${trail.length?' · Aprofundamento':''}`;
  $('#context-title').textContent=s.id==='encerramento'?s.group:`${s.group} · ${plain(s.title.replace(/<br>/g,' '))}`;
  $('#context-bridge').textContent=s.route_bridges?.[trail.length?'estendido':mode]||s.bridge;
  $('#progress-fill').style.width=`${Math.max(0,(idx+1)/r.length)*100}%`;
  $('#btn-prev').disabled=navIndex<=0;
  $('#btn-next').disabled=navIndex===ids.length-1;
  $('#btn-next').textContent='Próximo →';
  $('#return-strip').hidden=!trail.length;
  if(trail.length)$('#return-strip').textContent=`↩ Voltar a “${plain(byId[trail[trail.length-1]].title.replace(/<br>/g,' '))}”`;
  $('#route-summary').innerHTML=`<strong>${modeLabel()}</strong><br>${mode==='executivo'?'Mensagens principais, visão, big bets e discussão.':'Percurso completo, com os casos e suas transições em sequência.'} Use as setas para avançar; “Aprofundar” abre a leitura do tema.`;
  $('#comparison-content').innerHTML=DATA.compare[comparison];
  $('#btn-notes').textContent=notes[current]?'Discussão •':'Discussão';
  document.title=`${plain(s.title.replace(/<br>/g,' '))} · IA | VP Pessoas`;
  scaleDeck();announce(`${idx+1>0?'Quadro '+(idx+1)+'. ':''}${plain(s.title.replace(/<br>/g,' '))}`);
}
function go(id,{drill=false,replace=false,preserveTrail=false}={}){if(!byId[id])return;closeDialog(false);if(id===current)return;if(drill)trail.push(current);else if(!preserveTrail)trail=[];trail=trail.filter(x=>x!==id);current=id;render();setHash(replace);if(matchMedia('(max-width:700px)').matches)window.scrollTo(0,0);$('.active .screen-title')?.focus({preventScroll:true});}
function backToOrigin(){if(!trail.length)return;closeDialog(false);current=trail.pop();render();setHash();$('.active .screen-title')?.focus({preventScroll:true});}
function step(delta){const ids=navigation(),idx=ids.indexOf(current),next=ids[idx+delta];if(next)go(next,{preserveTrail:true});}
function changeMode(value){if(!DATA.routes[value]||value===mode)return;mode=value;const ids=route();if(!ids.includes(current)){const order=DATA.slides.map(s=>s.id),before=order.indexOf(current);current=[...ids].reverse().find(id=>order.indexOf(id)<=before)||ids[0];}trail=[];closeDialog(false);render();setHash();toast(`Modo ${modeLabel()} selecionado.`);}
function openDialog(title,body,{wide=false}={}){const d=$('#workspace-dialog');if(!d.open)lastFocus=document.activeElement;$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;d.style.width=wide?'min(1140px,calc(100vw - 24px))':'';if(!d.open)d.showModal();$('#dialog-body').scrollTop=0;$('.dialog-close').focus();}
function closeDialog(restore=true){const d=$('#workspace-dialog');if(d.open){d.close();if(restore&&lastFocus?.isConnected)lastFocus.focus({preventScroll:true});}}
function reading(chapter=active().chapter,section=active().section){const ch=DATA.chapters[chapter];if(!ch)return;const s=active();openDialog('Leitura aprofundada',`<div class="reader"><div class="reading-intro"><strong>Estratégia V2 · capítulo ${chapter}</strong><br>Conteúdo do documento vigente, revisão de 06/09/2026. A leitura está incorporada a este arquivo.<small>Os links públicos abrem em outra aba. Referências ao acervo local mantêm os caminhos do projeto.</small></div><div class="reading-actions"><button class="plain-btn" data-open-sources="current">Fontes deste quadro</button><button class="plain-btn" data-discuss>Discutir este tema</button></div>${s.detail.length?'<div class="detail-links">'+s.detail.map(id=>`<button class="drill" data-jump="${id}">${esc(plain(byId[id].title.replace(/<br>/g,' ')))} ↗</button>`).join('')+'</div>':''}${ch}</div>`,{wide:true});if(section){const target=$(`[data-section="${section}"]`,$('#dialog-body'));if(target)$('#dialog-body').scrollTop=target.offsetTop-$('#dialog-body').offsetTop-15;}}
function sourceCard(s){const publicSource=!!s.url;return `<article class="source-card"><div class="sources-meta"><span class="tag">${publicSource?'Fonte pública':'Fonte do acervo'}</span><small>${esc(s.id)}</small></div><h3>${esc(s.title)}</h3>${s.published?`<small>Publicação / referência: ${esc(s.published)}</small>`:''}<p>${esc(s.description||s.locator||'Referência catalogada no projeto.')}</p>${s.limitations?`<p class="source-limit"><strong>Como interpretar:</strong> ${esc(s.limitations)}</p>`:''}<a href="${esc(s.url||s.href)}" target="_blank" rel="noopener noreferrer">${publicSource?'Abrir publicação original':'Abrir arquivo do acervo'} ↗</a>${s.excerpt?`<details><summary class="text-link">Ler síntese do acervo neste HTML</summary><div class="reader">${s.excerpt}</div></details>`:''}</article>`;}
function sourceIds(){if(sourceFilter==='current')return active().sources;return Object.keys(DATA.sources);}
function drawSources(){const q=($('#source-search')?.value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();let ids=sourceIds();if(sourceFilter==='public')ids=ids.filter(id=>DATA.sources[id].url);if(sourceFilter==='local')ids=ids.filter(id=>!DATA.sources[id].url);const filtered=ids.filter(id=>{const s=DATA.sources[id];return[s.id,s.title,s.description,s.locator].join(' ').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q);});$('#sources-list').innerHTML=filtered.map(id=>sourceCard(DATA.sources[id])).join('')||'<p>Nenhuma fonte encontrada neste filtro. Tente “Todas” ou outro termo.</p>';$('#source-count').textContent=`${filtered.length} referência${filtered.length===1?'':'s'}`;}
function sources(filter='all'){sourceFilter=filter;openDialog('Fontes e evidências',`<p>Abra a publicação citada ou consulte a síntese incorporada das fontes locais. Cada referência preserva sua natureza e seus limites.</p><div class="segmented" role="group" aria-label="Filtrar fontes">${[['all','Todas'],['current','Deste quadro'],['public','Públicas'],['local','Acervo']].map(([id,t])=>`<button data-source-filter="${id}" aria-pressed="${filter===id}">${t}</button>`).join('')}</div><label class="notes-label" for="source-search">Buscar por empresa, assunto ou código</label><input id="source-search" type="search" class="search-field" placeholder="Ex.: Nubank, dados, SRC-PUB-021"><small id="source-count" aria-live="polite"></small><div id="sources-list"></div>`);drawSources();}
function showSource(id){const s=DATA.sources[id];if(s)openDialog('Fonte da evidência',sourceCard(s)+`<button class="plain-btn" data-open-sources="current" style="margin-top:20px">Ver fontes deste quadro</button>`);}
function map(group=''){const ids=route();openDialog('Mapa da conversa',`<p>Modo <strong>${modeLabel()}</strong>. Selecione um tema para abrir. Nos aprofundamentos, as setas seguem a sequência completa e o botão de retorno preserva seu ponto de partida.</p><label class="notes-label" for="map-search">Encontrar um tema</label><input type="search" class="search-field" id="map-search" placeholder="Ex.: plataformas, competências, visão"><div id="map-list">${[...new Set(DATA.slides.map(s=>s.group))].map(g=>`<section class="map-group" data-group="${g}"><h3>${g}</h3><div class="map-items">${DATA.slides.filter(s=>s.group===g).map(s=>`<button class="map-item${s.id===current?' current':''}" data-map-slide="${s.id}" aria-current="${s.id===current?'step':'false'}"><b>${ids.includes(s.id)?String(ids.indexOf(s.id)+1).padStart(2,'0'):'↗'}</b><span><strong>${esc(plain(s.title.replace(/<br>/g,' ')))}</strong><small>${ids.includes(s.id)?'Neste percurso':'Aprofundamento disponível'}</small></span></button>`).join('')}</div></section>`).join('')}</div>`,{wide:true});if(group){const el=$(`[data-group="${group}"]`);if(el)$('#dialog-body').scrollTop=el.offsetTop-$('#dialog-body').offsetTop;}}
function discuss(){const s=active();openDialog('Caderno da discussão',`<p>${esc(plain(s.title.replace(/<br>/g,' ')))}</p><div class="note-question">${esc(s.question||'Que entendimento e próximos passos queremos registrar?')}</div><label for="meeting-notes" class="notes-label">Registros deste tema</label><textarea id="meeting-notes" class="notes-area" placeholder="Convergências, ajustes, dúvidas, responsáveis e próximos esclarecimentos…">${esc(notes[current]||'')}</textarea><div class="note-footer"><span id="save-status">${canStore?'Notas ficam neste navegador. Exporte para guardar ou compartilhar.':'O navegador não permite salvar localmente. Exporte antes de fechar.'}</span><button class="primary-btn" data-export-notes>Exportar todas as notas</button></div>${s.note?`<details class="facilitator"><summary>Contexto para conduzir a discussão</summary><p>${esc(s.note)}</p></details>`:''}${s.detail.length?`<h3>Abrir um aprofundamento</h3><div class="detail-links">${s.detail.map(id=>`<button class="drill" data-jump="${id}">${esc(plain(byId[id].title.replace(/<br>/g,' ')))} ↗</button>`).join('')}</div>`:''}`);}
function saveNotes(value){notes[current]=value;try{localStorage.setItem(KEY,JSON.stringify(notes));canStore=true;$('#save-status').textContent='Salvo neste navegador. Exporte para guardar ou compartilhar.';}catch{canStore=false;$('#save-status').textContent='Nota mantida nesta sessão. Exporte antes de fechar.';}$('#btn-notes').textContent=value?'Discussão •':'Discussão';}
function exportNotes(){const used=DATA.slides.filter(s=>(notes[s.id]||'').trim());if(!used.length){toast('Ainda não há notas registradas.');return;}const now=new Date(),content=`# Registros da reunião — Estratégia de IA da VP Pessoas\n\nData da exportação: ${now.toLocaleString('pt-BR')}\n\n`+used.map(s=>`## ${plain(s.title.replace(/<br>/g,' '))}\n\nPergunta: ${s.question||'Discussão do tema'}\n\n${notes[s.id]}\n`).join('\n');const blob=new Blob(['\ufeff'+content],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`NOTAS_REUNIAO_VPP_${now.toISOString().slice(0,10)}.md`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast(`${used.length} tema(s) exportado(s).`);}
function help(){openDialog('Como conduzir a conversa',`<div class="reader"><p>Escolha o modo de visualização. O indicador mostra o percentual percorrido; nos aprofundamentos, preserva a posição do percurso principal.</p><h3>Dois modos</h3><div class="mode-guide"><div><b>Executivo</b>Mensagens principais, visão, big bets e discussão final.</div><div><b>Estendido</b>Percurso completo, com transições por empresa, casos, comparação e desenvolvimento das big bets.</div><div><b>Leitura livre</b>O mapa dá acesso a todos os quadros. “Aprofundar” abre o texto do capítulo correspondente.</div></div><h3>Navegação</h3><p><strong>← / →:</strong> quadro anterior ou próximo, inclusive dentro dos casos. <strong>Voltar a…:</strong> retorna ao ponto de partida de um aprofundamento. <strong>Esc:</strong> fecha a leitura ou volta do aprofundamento. <strong>M:</strong> mapa. <strong>A:</strong> aprofundar. <strong>D:</strong> discussão. <strong>F:</strong> apresentação em tela cheia. <strong>?:</strong> este guia.</p><p>Os atalhos ficam suspensos ao digitar ou usar os diálogos. Os botões oferecem as mesmas ações.</p><h3>Fontes e registros</h3><p>As publicações abrem em outra aba. O HTML e a leitura funcionam sem internet; os sites externos exigem conexão. Para abrir arquivos originais do acervo, mantenha este HTML na pasta do projeto. As notas ficam neste navegador quando permitido e podem ser exportadas em Markdown.</p><div class="reading-actions"><button class="plain-btn" data-print>Imprimir percurso / salvar PDF</button><button class="plain-btn" data-export-notes>Exportar notas</button><button class="plain-btn" data-fullscreen>Alternar tela cheia</button></div></div>`);}
async function fullScreen(){closeDialog();if(document.fullscreenElement){await document.exitFullscreen().catch(()=>{});document.body.classList.remove('presentation-mode');}else{document.body.classList.add('presentation-mode');if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen().catch(()=>toast('Modo apresentação ativado. Use F para sair.'));}scaleDeck();}
document.addEventListener('click',e=>{
 const el=e.target.closest('button,a');if(!el)return;
 if(el.dataset.mode)changeMode(el.dataset.mode);
 else if(el.dataset.jump)go(el.dataset.jump,{drill:!route().includes(el.dataset.jump)});
 else if(el.dataset.mapSlide){const id=el.dataset.mapSlide;go(id,{drill:!route().includes(id)});}
 else if(el.dataset.mapGroup)map(el.dataset.mapGroup);
 else if(el.dataset.source)showSource(el.dataset.source);
 else if(el.dataset.openSources)sources(el.dataset.openSources);
 else if(el.dataset.compare){comparison=el.dataset.compare;$$('[data-compare]').forEach(b=>b.setAttribute('aria-pressed',String(b===el)));$('#comparison-content').innerHTML=DATA.compare[comparison];}
 else if(el.dataset.layer!==undefined){$$('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',String(b===el)));$('#layer-detail').innerHTML=DATA.layers[Number(el.dataset.layer)];}
 else if(el.dataset.sourceFilter){sourceFilter=el.dataset.sourceFilter;$$('[data-source-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===el)));drawSources();}
 else if(el.hasAttribute('data-discuss'))discuss();
 else if(el.hasAttribute('data-export-notes'))exportNotes();
 else if(el.hasAttribute('data-fullscreen'))fullScreen();
 else if(el.hasAttribute('data-print')){closeDialog();document.body.classList.remove('presentation-mode');window.print();}
});
document.addEventListener('input',e=>{if(e.target.id==='meeting-notes')saveNotes(e.target.value);if(e.target.id==='source-search')drawSources();if(e.target.id==='map-search'){const q=e.target.value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();$$('.map-item').forEach(el=>el.hidden=!el.textContent.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q));$$('.map-group').forEach(el=>el.hidden=!$$('.map-item',el).some(x=>!x.hidden));}});
$('#btn-prev').addEventListener('click',()=>step(-1));$('#btn-next').addEventListener('click',()=>step(1));$('#return-strip').addEventListener('click',backToOrigin);$('#btn-map').addEventListener('click',()=>map());$('#btn-read').addEventListener('click',()=>reading());$('#btn-notes').addEventListener('click',discuss);$('#btn-help').addEventListener('click',help);$('.dialog-close').addEventListener('click',()=>closeDialog());
$('#workspace-dialog').addEventListener('click',e=>{if(e.target.id==='workspace-dialog'){const b=e.target.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)closeDialog();}});
$('#workspace-dialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#workspace-dialog').open){e.preventDefault();closeDialog();return;}if(e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select,[contenteditable]'))return;if($('#workspace-dialog').open)return;if(e.key==='Escape'){if(trail.length)backToOrigin();else if(document.body.classList.contains('presentation-mode')){document.body.classList.remove('presentation-mode');if(document.fullscreenElement)document.exitFullscreen().catch(()=>{});scaleDeck();}return;}if(e.target.closest('button,a')&&['Enter',' '].includes(e.key))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();step(1);}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();step(-1);}else if(e.key==='Home'){e.preventDefault();go(route()[0]);}else if(e.key==='End'){e.preventDefault();go(route().at(-1));}else if(e.key.toLowerCase()==='m')map();else if(e.key.toLowerCase()==='a')reading();else if(e.key.toLowerCase()==='d')discuss();else if(e.key.toLowerCase()==='f'){if(document.body.classList.contains('presentation-mode')&&!document.fullscreenElement){document.body.classList.remove('presentation-mode');scaleDeck();}else fullScreen();}else if(e.key==='?')help();});
window.addEventListener('popstate',()=>{closeDialog(false);parseHash();render();});window.addEventListener('hashchange',()=>{parseHash();render();});window.addEventListener('resize',scaleDeck);document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement)document.body.classList.remove('presentation-mode');scaleDeck();});
$$('.vpp-ppt-bg').forEach(img=>img.src=DATA.backgrounds[img.dataset.background]);
parseHash();render();setHash(true);document.fonts?.ready.then(scaleDeck);
